export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";


export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_ERROR = "FETCH_USER_ERROR";

// Details Config
export const FETCH_DETAILS_CONFIG_SUCCESS = "FETCH_DETAILS_CONFIG_SUCCESS";
export const FETCH_DETAILS_CONFIG_REQUEST = "FETCH_DETAILS_CONFIG_REQUEST";
export const FETCH_DETAILS_CONFIG_ERROR = "FETCH_DETAILS_CONFIG_ERROR";

//Fetch Now Playing
export const FETCH_NOW_PLAYING_SUCCESS = "FETCH_NOW_PLAYING_SUCCESS";
export const FETCH_NOW_PLAYING_REQUEST = "FETCH_NOW_PLAYING_REQUEST";
export const FETCH_NOW_PLAYING_ERROR = "FETCH_NOW_PLAYING_ERROR";


// Fetch Genres
export const FETCH_GENRES_SUCCESS = "FETCH_GENRES_SUCCESS";
export const FETCH_GENRES_REQUEST = "FETCH_GENRES_REQUEST";
export const FETCH_GENRES_ERROR = "FETCH_GENRES_ERROR";


//FETCH MOVIES BY GENRES
export const FETCH_MOVIES_BY_GENRES_REQUEST = "FETCH_MOVIES_BY_GENRES_REQUEST"
export const FETCH_MOVIES_BY_GENRES_SUCCESS = "FETCH_MOVIES_BY_GENRES_SUCCESS"
export const FETCH_MOVIES_BY_GENRES_ERROR = "FETCH_MOVIES_BY_GENRES_ERROR"

//FETCH TOP RATE
export const FETCH_TOP_RATE_REQUEST = "FETCH_TOP_RATE_REQUEST"
export const FETCH_TOP_RATE_SUCCESS = "FETCH_TOP_RATE_SUCCESS"
export const FETCH_TOP_RATE_ERROR = "FETCH_TOP_RATE_ERROR"

//FETCH CREDIT
export const FETCH_CREDIT_REQUEST = "FETCH_CREDIT_REQUEST"
export const FETCH_CREDIT_SUCCESS = "FETCH_CREDIT_SUCCESS"
export const FETCH_CREDIT_ERROR = "FETCH_CREDIT_ERROR"

//FETCH MOVIE DETAILS
export const FETCH_MOVIE_DETAILS_REQUEST = "FETCH_MOVIE_DETAILS_REQUEST"
export const FETCH_MOVIE_DETAILS_SUCCESS = "FETCH_MOVIE_DETAILS_SUCCESS"
export const FETCH_MOVIE_DETAILS_ERROR = "FETCH_MOVIE_DETAILS_ERROR"

//FETCH COMPANY
export const FETCH_COMPANY_REQUEST = "FETCH_COMPANY_REQUEST"
export const FETCH_COMPANY_SUCCESS = "FETCH_COMPANY_SUCCESS"
export const FETCH_COMPANY_ERROR = "FETCH_COMPANY_ERROR"

//FETCH REVIEWS
export const FETCH_REVIEWS_REQUEST = "FETCH_REVIEWS_REQUEST"
export const FETCH_REVIEWS_SUCCESS = "FETCH_REVIEWS_SUCCESS"
export const FETCH_REVIEWS_ERROR = "FETCH_REVIEWS_ERROR"

export const FETCH_VIDEO_REQUEST = "FETCH_VIDEO_REQUEST"
export const FETCH_VIDEO_SUCCESS = "FETCH_VIDEO_SUCCESS"
export const FETCH_VIDEO_ERROR = "FETCH_VIDEO_ERROR"